on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: tamojrn.azurecr.io
        username: ${{ secrets.acr_tamojrn_username }}
        password: ${{ secrets.acr_tamojrn_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t tamojrn.azurecr.io/angularkcn:${{ github.sha }}
        docker push tamojrn.azurecr.io/angularkcn:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_angularkcn_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep angularkcnb71b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace angularkcnb71b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: angularkcnb71b
        container-registry-url: tamojrn.azurecr.io
        container-registry-username: ${{ secrets.acr_tamojrn_username }}
        container-registry-password: ${{ secrets.acr_tamojrn_password }}
        secret-name: angularkcndockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: angularkcnb71b
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          tamojrn.azurecr.io/angularkcn:${{ github.sha }}
        imagepullsecrets: |
          angularkcndockerauth